# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: record.proto for package ''

require 'grpc'

module RecordService
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'RecordService'

    rpc :GetRecord, ::GetRecordReq, ::GetRecordRes
  end

  Stub = Service.rpc_stub_class
end
